apiVersion: v1
kind: Service
metadata:
  name: piss-server-service
spec:
  type: LoadBalancer
  ports:
  - port: 44000
    targetPort: 44000
    nodePort: 30001
    protocol: UDP
    name: server-port
  selector:
    app: piss-server
