name: Docker Image CI

on: [push]

jobs:
  test-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build -t "piss-server" .
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'piss-server'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH'

  push-docker-image:
    needs: [ test-docker-image]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build Docker image
      run: docker build -t "piss-server" .
    - name: Docker Tag
      run: docker tag "piss-server" ${{ secrets.DOCKERHUB_USERNAME }}"/piss-server"
    - name: Docker Push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}"/piss-server"