name: Docker Image CI

on: [push]

jobs:
  build-java-app:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v1
      with:
        java-version: 21
    - name: Build with Maven - Client
      run: mvn -B package --file client/pom.xml
    - name: Build with Maven - Server
      run: mvn -B package --file server/pom.xml
    - name: Save new repo as artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: ./

  test-docker-image:
    needs: [ build-java-app ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: build-artifact
        path: ./
    - name: Build Docker image
      run: docker build -t "piss-server" .
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'piss-server'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        severity: 'CRITICAL'

  push-docker-image:
    needs: [ test-docker-image]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: build-artifact
        path: ./
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build Docker image
      run: docker build -t "piss-server" .
    - name: Docker Tag
      run: docker tag "piss-server" ${{ secrets.DOCKERHUB_USERNAME }}"/piss-server"
    - name: Docker Push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}"/piss-server"